### ISSUE TITLE
Authorization Failed to enable git button

### ISSUE THREAD

**Issue by BobbyJohansen** [manosim/gitify#355]
The authorization flow came up with github asking for access but the button to accept was disabled potentially due to browser support. Pasting the auth url in a supported browser resolved my issue.

**Comment by onesoma** [comment]
I see the same problem @BobbyJohansen. Could you let me know how you got the auth url?

**Comment by missinglink** [comment]
worked for me, but this is clearly very broken right now.
as a new user, after downloading the app the first thing you experience is confusion and frustration.

I also had a warning at the top of the browser window saying that "this browser is no longer supported"

**Comment by OranShusterSpotinst** [comment]
Does not work for me 
href from window - 
`https://github.com/login/oauth/authorize?client_id=27a352516d3341cee376&scope=user:email,notifications`

**Comment by riastrad** [comment]
I also hit this problem today, and the above step resolved the issue. 

One additional detail that might be worthing noting for me - when auth'ing via Firefox's latest (66.0.2) - is that after pasting the auth url, the browser was redirected to an invalid `localhost` callback. Returning to the Desktop app and clicking the sign in again successfully loaded the app with my account.

**Comment by peposure** [comment]
> I also hit this problem today, and the above step resolved the issue.
> 
> One additional detail that might be worthing noting for me - when auth'ing via Firefox's latest (66.0.2) - is that after pasting the auth url, the browser was redirected to an invalid `localhost` callback. Returning to the Desktop app and clicking the sign in again successfully loaded the app with my account.

I had to do this last step also, and it works ;)

**Comment by DonRichards** [comment]
I missed this ticket and ultimately duplicated. Here's the screenshot I post, hope this helps. ![Screen Shot 2019-06-24 at 12 32 18 PM](https://user-images.githubusercontent.com/2738244/60036676-c1eb1c00-967d-11e9-9999-e801fa5021cf.jpg)

**Comment by JakeSidSmith** [comment]
Seems that you can now just hit "Ignore" and login without issues. Though I think the real solution is to publish a new version of Gitify with an updated version of electron.

**Comment by designsimply** [comment]
I ran into this issue and found it very confusing! The "Authorize" button is inactive, even after clicking" Ignore in the browser no longer supported warning notice at the top of the popup window.

<img src="https://user-images.githubusercontent.com/1119271/62399261-752a1900-b538-11e9-893a-2582926936e7.png" width="540" alt="Screen Shot 2019-08-02 at 3 14 49 PM">

The workaround @jclifford-zd posted in asdf worked for me eventually though. Thanks @jclifford-zd !

**Comment by zenspider** [comment]
@JakeSidSmith nope. Ignore didn't activate the button for me.

**Comment by JakeSidSmith** [comment]
Previously I've fixed this by doing the following (which _may_ still work):

1. Open inspector (`CMD` + `ALT` + `i`, or `CTRL` + `ALT` + `i`?)
2. Select the button (using the element selector tool)
3. Delete the `disabled` attribute (double click the attribute in the inspector, select all text, delete)
4. Click the button

May be easier than accessing the URL and opening in the browser.

Haven't tested recently as I'd rather not log out of my accounts.

**Comment by wandergeek** [comment]
This is still broken in the latest build. Had to resort to the console hacks described above to make it work.

**Comment by git-ness** [comment]
Me too, I am on Mac OSX and also had to use the hack above to get the auth url today. Any hope to get this fixed in the near future?

**Comment by ianpaschal** [comment]
Ran into this today (see comment date) on v2.0.2. Work-around with copying the URL works, but it's pretty ugly.

**Comment by vicbergquist** [comment]
Ran into this issue today (Version 2.0.2), inspected the HTML and removed the `disabled` attribute on the auth button and it worked 😊

**Comment by manosim** [comment]
Hi everyone, sorry for the confusion - Gitify went through a massive rewrite and this should now be fixed in v3. Let me know if it's not and I'm happy to investigate further.
